import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

type InvoiceItem = {
  description: string;
  price: number;
};

type GeneratePdfArgs = {
  invoiceId: number;
  invoiceCode: string;
  createdAtISO: string;
  dueDateISO?: string;
  customerName?: string;
  customerAddress?: string;
  customerEmail?: string;
  customerPhone?: string;
  items: InvoiceItem[];
  subtotal: number;
  discount: number;
  dpp: number;
  taxRate: number; // 0.11
  taxAmount: number;
  grandTotal: number;
};

const money = (n: number) =>
  new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(n);

export async function generateInvoicePdf(args: GeneratePdfArgs) {
  const publicDir = path.join(__dirname, "..", "..", "public", "invoices");
  fs.mkdirSync(publicDir, { recursive: true });

  const filename = `invoice-${args.invoiceId}.pdf`;
  const fullPath = path.join(publicDir, filename);

  return await new Promise<{ fullPath: string; filename: string }>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 40 });
    const stream = fs.createWriteStream(fullPath);

    stream.on("finish", () => resolve({ fullPath, filename }));
    stream.on("error", reject);

    doc.pipe(stream);

    // Header
    doc.fontSize(18).text("INVOICE", 0, 40, { align: "center" });
    doc.moveDown(0.5);

    // Left header (issuer placeholder)
    doc.fontSize(10).text("FUFU Invoice System", 40, 70);
    doc.fontSize(9).fillColor("#444").text("Auto-generated invoice PDF", 40, 84);
    doc.fillColor("#000");

    // Right header fields (hide if empty)
    const rightX = 360;
    let rightY = 70;
    const line = (label: string, value?: string) => {
      if (!value) return;
      doc.fontSize(9).text(`${label}: ${value}`, rightX, rightY);
      rightY += 14;
    };

    line("Number", args.invoiceCode);
    line("Inv. Date", args.createdAtISO.slice(0, 10));
    if (args.dueDateISO) line("Due Date", args.dueDateISO);

    // Divider
    doc.moveTo(40, 130).lineTo(555, 130).strokeColor("#cccccc").stroke();
    doc.strokeColor("#000");

    // Customer block (hide missing lines)
    let customerY = 145;
    if (
      args.customerName ||
      args.customerAddress ||
      args.customerEmail ||
      (args.customerPhone && args.customerPhone !== "0")
    ) {
      doc.fontSize(10).text("Customer", 40, customerY);
      customerY += 14;
      doc.fontSize(9);
      if (args.customerName) doc.text(args.customerName, 40, customerY), (customerY += 12);
      if (args.customerAddress) doc.text(args.customerAddress, 40, customerY), (customerY += 12);
      if (args.customerEmail) doc.text(`Email: ${args.customerEmail}`, 40, customerY), (customerY += 12);
      if (args.customerPhone && args.customerPhone !== "0")
        doc.text(`Phone: ${args.customerPhone}`, 40, customerY), (customerY += 12);
    }

    // Table header
    const tableTop = 220;
    doc.moveTo(40, tableTop).lineTo(555, tableTop).strokeColor("#000").stroke();
    doc.fontSize(9).text("No.", 40, tableTop + 8);
    doc.text("Product Description", 70, tableTop + 8);
    doc.text("Net Amount", 470, tableTop + 8, { width: 85, align: "right" });
    doc.moveTo(40, tableTop + 26).lineTo(555, tableTop + 26).strokeColor("#000").stroke();

    // Items
    let y = tableTop + 36;
    const rowH = 16;
    args.items.forEach((it, idx) => {
      const desc = (it.description || "Item").trim();
      doc.fontSize(9).text(String(idx + 1), 40, y);
      doc.text(desc, 70, y, { width: 380 });
      doc.text(money(Number(it.price || 0)), 470, y, { width: 85, align: "right" });
      y += rowH;
    });

    // Totals block (right)
    const totalsX = 360;
    let totalsY = Math.max(y + 10, 420);
    const totalLine = (label: string, value: string, bold = false) => {
      doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(9);
      doc.text(label, totalsX, totalsY);
      doc.text(value, 470, totalsY, { width: 85, align: "right" });
      totalsY += 14;
    };

    totalLine("Gross Total", money(args.subtotal));
    if (args.discount > 0) totalLine("Discount Total", `- ${money(args.discount)}`);
    totalLine("DPP", money(args.dpp));
    totalLine(`Tax (${Math.round(args.taxRate * 100)}%)`, money(args.taxAmount));
    doc.moveTo(totalsX, totalsY + 2).lineTo(555, totalsY + 2).strokeColor("#000").stroke();
    totalsY += 8;
    totalLine("Net Total", money(args.grandTotal), true);

    // Footer note
    doc.font("Helvetica").fontSize(8).fillColor("#666");
    doc.text(
      "Generated by FUFU. Fields not provided by user are hidden automatically.",
      40,
      780,
      { width: 515, align: "center" }
    );
    doc.fillColor("#000");

    doc.end();
  });
}


